apiVersion: v1
kind: Namespace
metadata:
  name: wordpress
---
apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secrets
  namespace: wordpress
type: Opaque
stringData:
  wordpress-db-password: change-me-wordpress-db-password
  mysql-root-password: change-me-mysql-root-password
